version: '3.9'
services:
  monkey_automation_service:
    image: monkey_automation_service:0.0.1
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: monkey_automation_service
    environment:
      MONKEY_AUTOMATION_LANGUAGE: ES
      MONKEY_AUTOMATION_PORT: 8010
    volumes:
      - type: bind
        source: /lib/libpigpio.so.1
        target: /lib/libpigpio.so.1
        read_only: true
    ports:
      - "8080:8010"
    networks:
      - monkey-automation-network
networks:
  monkey-automation-network:
    name: monkey-automation-network